version: '3.8'

services:
  # Фронтенд
  frontend:
    build: 
      context: ./frontend
      target: prod
    container_name: project_e_frontend_prod
    volumes:
      - ./frontend/dist:/var/www/project_e/dist
    env_file:
      - ./frontend/.env.production
    networks:
      - custom

  # Nginx
  nginx:
    image: nginx:latest
    container_name: project_e_nginx_prod
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./nginx/server.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
      - ./frontend/dist:/var/www/project_e/dist
    depends_on:
      - frontend
      - backend
    networks:
      - custom

  # Админ панель
  admin_panel:
    build: ./adminka
    volumes:
      - ./adminka:/app
      - /app/.venv
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
    ports:
      - "6786:6786"
    networks:
      - custom

  # Бэкенд
  backend:
    build: 
      context: ./backend
      target: prod
    container_name: project_e_backend_prod
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - custom

  # База данных
  db:
    image: postgres
    container_name: project_e_db_prod
    environment:
      POSTGRES_DB: project_e
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - custom

networks:
  custom:
    driver: bridge