version: '3.8'

services:
  # Фронтенд
  frontend:
    build: 
      context: ./frontend
      target: prod
    container_name: project_e_frontend_local
    volumes:
      - frontend_dist:/app/dist
    env_file:
      - ./frontend/.env.production
    networks:
      - custom

  # Nginx
  nginx:
    image: nginx:latest
    container_name: project_e_nginx_local
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/local.conf:/etc/nginx/conf.d/default.conf  # Конфиг для localhost
      - ./nginx/certs:/etc/nginx/certs  # Самоподписанные сертификаты
      - frontend_dist:/var/www/project_e/dist
    depends_on:
      - frontend
      - backend
    networks:
      - custom

  # Админ панель
  admin_panel:
    build: ./adminka
    volumes:
      - ./adminka:/app
      - /app/.venv
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
    ports:
      - "6786:6786"
    networks:
      - custom

  # Бэкенд
  backend:
    build: 
      context: ./backend
      target: prod
    container_name: project_e_backend_local
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - custom

  # База данных
  db:
    image: postgres
    container_name: project_e_db_local
    environment:
      POSTGRES_DB: project_e
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - custom

volumes:
  frontend_dist:

networks:
  custom:
    driver: bridge