services:
  #фронтенд
  frontend:
    build: 
      context: ./frontend
      target: dev
    container_name: project_e_frontend_dev
    command: npm run dev --host
    ports:
      - '5173:5173'
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /dev/null:/app/package-lock.json
    networks:
      - custom
      
  #админ панель нашего приложения
  admin_panel:
    build: ./adminka
    volumes:
      - ./adminka:/app
      - /app/.venv
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
    ports:
      - "6786:6786"
    networks:
      - custom

  support_bot:
    build: ./bot
    container_name: support_bot
    volumes:
      - ./bot:/app  # Монтируем текущую директорию в контейнер
    networks:
      - custom

  #основная апишка нашего приложения
  backend:
    build: 
      context: ./backend
      target: dev
    container_name: project_e_backend_dev
    # command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    volumes:
      - ./backend:/fastapi_app
      - /fastapi_app/.venv
    depends_on:
      - db
    networks:
      - custom

  # просто база данных для разработки
  db:
    image: postgres
    container_name: project_e_db
    environment:
      POSTGRES_DB: project_e
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - custom

  # база данных для прогона тестов
  test_db:
    image: postgres
    container_name: project_e_test_db
    environment:
      POSTGRES_DB: v
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    networks:
      - custom

networks:
  custom:
    driver: bridge