"""basic associations mod

Revision ID: 4d0bb6b4dbcc
Revises: b6a9a1987e70
Create Date: 2024-09-17 22:39:24.009439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d0bb6b4dbcc'
down_revision: Union[str, None] = 'b6a9a1987e70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_classroom_associations',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('classroom_id', sa.Uuid(), nullable=False),
    sa.Column('student_best_task_type', sa.Integer(), nullable=True),
    sa.Column('student_best_task_percent', sa.Integer(), nullable=True),
    sa.Column('student_worst_task_type', sa.Integer(), nullable=True),
    sa.Column('student_worst_task_percent', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], name=op.f('fk_student_classroom_associations_classroom_id_classrooms')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_student_classroom_associations_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_classroom_associations')),
    sa.UniqueConstraint('student_id', 'classroom_id', name='idx_unique_student_classroom')
    )
    op.create_table('student_variant_associations',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_student_variant_associations_student_id_students')),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], name=op.f('fk_student_variant_associations_variant_id_variants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_variant_associations')),
    sa.UniqueConstraint('student_id', 'variant_id', name='idx_unique_student_variant')
    )
    op.create_table('variant_task_associations',
    sa.Column('variant_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_variant_task_associations_task_id_tasks')),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], name=op.f('fk_variant_task_associations_variant_id_variants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_variant_task_associations')),
    sa.UniqueConstraint('variant_id', 'task_id', name='idx_unique_variant_task')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variant_task_associations')
    op.drop_table('student_variant_associations')
    op.drop_table('student_classroom_associations')
    # ### end Alembic commands ###
