"""deleting stud and teach tables

Revision ID: 30f11832471d
Revises: 1897ff8b6ba1
Create Date: 2024-11-20 09:54:01.176382

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "30f11832471d"
down_revision: Union[str, None] = "1897ff8b6ba1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE students CASCADE")
    op.execute("DROP TABLE teachers CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teachers",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("subject", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["id"], ["users.id"], name="fk_teachers_id_users"),
        sa.PrimaryKeyConstraint("id", name="pk_teachers"),
    )
    op.create_table(
        "students",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["id"], ["users.id"], name="fk_students_id_users", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_students"),
    )
    # ### end Alembic commands ###
