"""added total task in variant

Revision ID: d5a7da73ec7a
Revises: b8941cb7aeb9
Create Date: 2024-10-07 12:33:29.029341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5a7da73ec7a'
down_revision: Union[str, None] = 'b8941cb7aeb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variants', sa.Column('total_tasks', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variants', 'total_tasks')
    # ### end Alembic commands ###
