"""made file_id in tasks nullable

Revision ID: cc1d026d13a1
Revises: 82d010683013
Create Date: 2024-10-12 18:11:48.904842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc1d026d13a1'
down_revision: Union[str, None] = '82d010683013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'file_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'file_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
