"""added ondel=cascade where it lacked

Revision ID: b0072bac2596
Revises: 30f11832471d
Create Date: 2025-01-06 21:48:08.146446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0072bac2596'
down_revision: Union[str, None] = '30f11832471d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_student_classroom_associations_classroom_id_classrooms', 'student_classroom_associations', type_='foreignkey')
    op.drop_constraint('fk_student_classroom_associations_student_id_users', 'student_classroom_associations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_student_classroom_associations_classroom_id_classrooms'), 'student_classroom_associations', 'classrooms', ['classroom_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_student_classroom_associations_student_id_users'), 'student_classroom_associations', 'users', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_student_variant_associations_variant_id_variants', 'student_variant_associations', type_='foreignkey')
    op.drop_constraint('fk_student_variant_associations_student_id_users', 'student_variant_associations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_student_variant_associations_variant_id_variants'), 'student_variant_associations', 'variants', ['variant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_student_variant_associations_student_id_users'), 'student_variant_associations', 'users', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_variant_task_associations_variant_id_variants', 'variant_task_associations', type_='foreignkey')
    op.drop_constraint('fk_variant_task_associations_task_id_tasks', 'variant_task_associations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_variant_task_associations_variant_id_variants'), 'variant_task_associations', 'variants', ['variant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_variant_task_associations_task_id_tasks'), 'variant_task_associations', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_variant_task_associations_task_id_tasks'), 'variant_task_associations', type_='foreignkey')
    op.drop_constraint(op.f('fk_variant_task_associations_variant_id_variants'), 'variant_task_associations', type_='foreignkey')
    op.create_foreign_key('fk_variant_task_associations_task_id_tasks', 'variant_task_associations', 'tasks', ['task_id'], ['id'])
    op.create_foreign_key('fk_variant_task_associations_variant_id_variants', 'variant_task_associations', 'variants', ['variant_id'], ['id'])
    op.drop_constraint(op.f('fk_student_variant_associations_student_id_users'), 'student_variant_associations', type_='foreignkey')
    op.drop_constraint(op.f('fk_student_variant_associations_variant_id_variants'), 'student_variant_associations', type_='foreignkey')
    op.create_foreign_key('fk_student_variant_associations_student_id_users', 'student_variant_associations', 'users', ['student_id'], ['id'])
    op.create_foreign_key('fk_student_variant_associations_variant_id_variants', 'student_variant_associations', 'variants', ['variant_id'], ['id'])
    op.drop_constraint(op.f('fk_student_classroom_associations_student_id_users'), 'student_classroom_associations', type_='foreignkey')
    op.drop_constraint(op.f('fk_student_classroom_associations_classroom_id_classrooms'), 'student_classroom_associations', type_='foreignkey')
    op.create_foreign_key('fk_student_classroom_associations_student_id_users', 'student_classroom_associations', 'users', ['student_id'], ['id'])
    op.create_foreign_key('fk_student_classroom_associations_classroom_id_classrooms', 'student_classroom_associations', 'classrooms', ['classroom_id'], ['id'])
    # ### end Alembic commands ###
