"""added ondel=cascade

Revision ID: 1dd9df7c967b
Revises: b0072bac2596
Create Date: 2025-01-06 22:34:45.118068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dd9df7c967b'
down_revision: Union[str, None] = 'b0072bac2596'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_student_classroom_associations_student_id_users', 'student_classroom_associations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_student_classroom_associations_student_id_users'), 'student_classroom_associations', 'users', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_student_classroom_associations_student_id_users'), 'student_classroom_associations', type_='foreignkey')
    op.create_foreign_key('fk_student_classroom_associations_student_id_users', 'student_classroom_associations', 'users', ['student_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
