"""added points for tasks table

Revision ID: cd95974ca27f
Revises: 1dd9df7c967b
Create Date: 2025-01-17 09:35:47.905016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd95974ca27f'
down_revision: Union[str, None] = '1dd9df7c967b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('points_per_task', sa.Integer(), nullable=False))
    op.add_column('variants', sa.Column('amount_of_tasks', sa.Integer(), nullable=False))
    op.add_column('variants', sa.Column('maximum_score_from_short_answer_task', sa.Integer(), nullable=False))
    op.drop_column('variants', 'total_tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variants', sa.Column('total_tasks', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('variants', 'maximum_score_from_short_answer_task')
    op.drop_column('variants', 'amount_of_tasks')
    op.drop_column('tasks', 'points_per_task')
    # ### end Alembic commands ###
