"""added name for variant

Revision ID: c9505ba4b89d
Revises: cd95974ca27f
Create Date: 2025-02-01 21:03:55.147134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9505ba4b89d'
down_revision: Union[str, None] = 'cd95974ca27f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variants', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variants', 'name')
    # ### end Alembic commands ###
