"""added classroom_id to student_variant_assoc

Revision ID: c06756dcb5a1
Revises: 74b2d4b0c2f6
Create Date: 2025-03-02 16:50:33.512920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c06756dcb5a1'
down_revision: Union[str, None] = '74b2d4b0c2f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_variant_associations', sa.Column('classroom_id', sa.Uuid(), nullable=False))
    op.drop_constraint('fk_student_variant_associations_student_id_users', 'student_variant_associations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_student_variant_associations_student_id_users'), 'student_variant_associations', 'users', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_student_variant_associations_student_id_users'), 'student_variant_associations', type_='foreignkey')
    op.create_foreign_key('fk_student_variant_associations_student_id_users', 'student_variant_associations', 'users', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_column('student_variant_associations', 'classroom_id')
    # ### end Alembic commands ###
