"""added 2nd file to task

Revision ID: c31dd8f6a444
Revises: c06756dcb5a1
Create Date: 2025-03-12 18:15:05.558342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c31dd8f6a444'
down_revision: Union[str, None] = 'c06756dcb5a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_variant_association')
    op.drop_table('variant_task_association')
    op.create_unique_constraint('idx_unique_student_variant', 'student_variant_associations', ['student_id', 'variant_id'])
    op.add_column('tasks', sa.Column('additional_file_id', sa.Uuid(), nullable=True))
    op.add_column('tasks', sa.Column('additional_file_extension', sa.String(), nullable=True))
    op.create_unique_constraint('idx_unique_variant_task', 'variant_task_associations', ['variant_id', 'task_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('idx_unique_variant_task', 'variant_task_associations', type_='unique')
    op.drop_column('tasks', 'additional_file_extension')
    op.drop_column('tasks', 'additional_file_id')
    op.drop_constraint('idx_unique_student_variant', 'student_variant_associations', type_='unique')
    op.create_table('variant_task_association',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('variant_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='fk_variant_task_association_task_id_tasks'),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], name='fk_variant_task_association_variant_id_variants'),
    sa.PrimaryKeyConstraint('id', name='pk_variant_task_association'),
    sa.UniqueConstraint('variant_id', 'task_id', name='idx_unique_variant_task')
    )
    op.create_table('student_variant_association',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('variant_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], name='fk_student_variant_association_variant_id_variants'),
    sa.PrimaryKeyConstraint('id', name='pk_student_variant_association'),
    sa.UniqueConstraint('student_id', 'variant_id', name='idx_unique_student_variant')
    )
    # ### end Alembic commands ###
